version: '3'

services:
  lavalink-server:
    image: fredboat/lavalink:master
    volumes: 
      - "./configs/lavalink:/opt/Lavalink/config"
      - "./data:/opt/Lavalink/data"

  beanbot:
    build: .
    volumes: 
      - "./configs/:/configs"
    environment:
      - BOT_CONFIG_FILE=/configs/application.yaml
