version: '3'

services:
  lavalink-server:
    image: fredboat/lavalink:3.7.7
    volumes: 
      - "./configs/lavalink:/opt/Lavalink/config"
      - "./data:/opt/Lavalink/data"
    restart: unless-stopped

  beanbot:
    build: .
    volumes: 
      - "./configs/:/configs"
    environment:
      - BOT_CONFIG_FILE=/configs/application.yaml
      # - BOT_DEV=true
    restart: unless-stopped
