[version]
path = "src/beanbot/__about__.py"

[envs.default]
dependencies = [
  "black>=23.7.0",
  "mypy>=1.4.1",
  "ruff<0.0.280",
]

# hatch run all
# hatch run fmt
[envs.default.scripts]
typing = "mypy --install-types --non-interactive ."
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]